spring.application.name=smart-poultry-farm

spring.datasource.url=jdbc:mysql://localhost:3306/poultry_management
spring.datasource.username=root
spring.datasource.password=aq12ws#@5171SH

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true